# Generated by Django 5.1.4 on 2024-12-20 04:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('required_amount', models.CharField(max_length=255)),
                ('need_time', models.CharField(max_length=50)),
                ('bank_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
