# Generated by Django 5.1.4 on 2024-12-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loanapplication_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk', models.CharField(max_length=10)),
                ('budget', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_pin_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
