# Generated by Django 5.1.4 on 2025-01-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactformsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormSubmission',
            new_name='Contact',
        ),
    ]
